version: '2'
services:
  elasticsearch:
    image: elasticsearch:5.6.10-alpine
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - "ES_JAVA_OPTS=-Xms256m -Xmx1024m"
      - "discovery.type=single-node"
    command: -Enetwork.host=0.0.0.0 -Ediscovery.type=single-node